version: '3.7'

services:
    Customerservice:
        container_name: Customerservice
        tty: true
        image: Customerservice:latest
        build:
            context: ../src
            dockerfile: dockerfile
        ports:
            - "5100:5100"
        environment:
            - Spring__Cloud__Config__Uri=${Spring_Cloud_Config_Uri_VAL}
            - Spring__Cloud__Config__Username=${Spring_Cloud_Config_Username_VAL}
            - Spring__Cloud__Config__Password=${Spring_Cloud_Config_Password_VAL}
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT_VAL}
            - ASPNETCORE_URLS=${ASPNETCORE_URLS_VAL}
        networks:
            - Customernetwork    




